"""
Demo mode — simulates a real Claude response and executes the steps for real.
Task: "Create a Python project, write a calculator script, and run it."
"""

DEMO_TASK = 'Create a Python project called fable-demo, write a calculator script inside it, and run it'

DEMO_STEPS = [
    {
        "action": "shell",
        "params": {"command": "mkdir -p /tmp/fable-demo"},
        "description": "Create project directory fable-demo"
    },
    {
        "action": "file_write",
        "params": {
            "path": "/tmp/fable-demo/calculator.py",
            "content": (
                "def add(a, b): return a + b\n"
                "def sub(a, b): return a - b\n"
                "def mul(a, b): return a * b\n"
                "def div(a, b): return a / b if b != 0 else 'Error: division by zero'\n\n"
                "if __name__ == '__main__':\n"
                "    print('=== Fable Demo Calculator ===')\n"
                "    print(f'10 + 5  = {add(10, 5)}')\n"
                "    print(f'10 - 5  = {sub(10, 5)}')\n"
                "    print(f'10 x 5  = {mul(10, 5)}')\n"
                "    print(f'10 / 5  = {div(10, 5)}')\n"
                "    print(f'10 / 0  = {div(10, 0)}')\n"
                "    print('=== Done ===')\n"
            )
        },
        "description": "Write calculator.py with basic math operations"
    },
    {
        "action": "file_write",
        "params": {
            "path": "/tmp/fable-demo/README.md",
            "content": "# fable-demo\n\nAuto-generated by Fable AI.\n\n```bash\npython calculator.py\n```\n"
        },
        "description": "Write README.md for the project"
    },
    {
        "action": "shell",
        "params": {"command": "python /tmp/fable-demo/calculator.py"},
        "description": "Run the calculator script"
    },
    {
        "action": "shell",
        "params": {"command": "ls -lh /tmp/fable-demo/"},
        "description": "Show the generated project files"
    }
]
